name: Datax Release
on:
  push:

env:
  MVN_VERSION: '3.6.3'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: maven
          architecture: x64
      - name: Build Hive
        run: |
          curl -L "https://dlcdn.apache.org/maven/maven-3/${MVN_VERSION}/binaries/apache-maven-${MVN_VERSION}-bin.tar.gz" | tar zx
          "apache-maven-${MVN_VERSION}/bin/mvn" clean package -Dspark.version=${SPARK_VERSION} -U clean package assembly:assembly -Dmaven.test.skip=true
      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: datax-${{ github.ref_name }}
          path: target/datax.tar.gz
      - name: Create release
        if: github.ref_type == 'tag'
        uses: ncipollo/release-action@v1.11.1
        with:
          name: datax-${{ github.ref_name }}
          allowUpdates: true
          replacesArtifacts: true
          artifacts: target/datax.tar.gz
